import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import NextJsCarousel from "../components/carousel";

export default function Home() {
	const router = useRouter();
	return (
		<div className={styles.container}>
			<Head>
				<title>Wee Macro</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.nav}>
				<Navbar />
			</div>
			<hr className="divider-order-line"></hr>
			{/* <div>
				<Carousel />
			</div> */}
			<div className="row">
				<NextJsCarousel />
			</div>
			{/* <div className="row healthtest">
				<div className="col-md-12 col-lg-6 col-sm-12 col-12 title-text-q">
					<h1 className={styles.headertext}>
						The health you <br></br> want is here.
					</h1>
					<h2 className={styles.foodheader}>Wee Macro</h2>
					<div className={styles.openaccbuttondiv}>
						<button
							className={styles.openaccbutton}
							onClick={() => {
								router.push("/order");
							}}
						>
							Order Now
						</button>
					</div>
				</div>

				<div className="col-md-6 col-sm-12 col-12 picture-media-q">
					<div className={styles.imgparent}>
						<div className={styles.foodphoto1}>
							<Image
								src="/images/foodphoto1.jpg"
								width="300"
								height="400"
								position="absolute"
							/>
						</div>

						<div className={styles.foodphoto2}>
							<Image
								src="/images/foodphoto2.jpg"
								width="400"
								height="550"
								position="relative"
							/>
						</div>
						<div className={styles.picturetxtdiv}></div>
					</div>
				</div>
			</div> */}
		</div>
	);
}
